baseURL = "https://benjaminreich.de"
title = "Benjamin Reich"

theme = "hugo-coder"

languageCode = "en"
defaultContentLanguage = "en"

paginate = 20

#pygmentsStyle = "vim"
#pygmentsCodeFences = true
#pygmentsCodeFencesGuessSyntax = true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "vim"
    tabWidth = 4

#disqusShortname = "yourdiscussshortname"

[params]
    author = "Benjamin Reich"
    description = "Benjamin Reich's personal website"
    keywords = "blog,developer,personal"
    info = "IT Student on duty!"
    avatarURL = "images/avatar.jpg"
    #gravatar = "john.doe@example.com"
    footerContent = "Made out of bits."

    dateFormat = "2. January 2006"

    hideFooter = false
    hideCredits = true
    hideCopyright = false
    since = 2020

    math = true

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorScheme = "auto"

    # Hide the toggle button, along with the associated vertical divider
    hideColorSchemeToggle = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = true

    # Custom CSS
    customCSS = []

    # Custom SCSS
    customSCSS = []

    # Custom JS
    customJS = []

    favicon_16 = "/images/favicon/favicon-16x16.png"
    favicon_32 = "/images/favicon/favicon-32x32.png"
    touchIcon = "/images/favicon/apple-touch-icon.png"


# If you want to use fathom(https://usefathom.com) for analytics, add this section
#[params.fathomAnalytics]
#    siteID = "ABCDE"
#    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
#    serverURL = "analytics.example.com"

# If you want to use plausible(https://plausible.io) for analytics, add this section
[params.plausibleAnalytics]
    domain = "benjaminreich.de"
    # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
    serverURL = "analytics.benjaminreich.de"

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
[params.goatCounter]
    code = "benjaminreich"

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
#[params.cloudflare]
#    token = "token"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/b-reich/"
    target = "_blank"
[[params.social]]
    name = "Gitlab"
    icon = "fa fa-gitlab"
    weight = 2
    url = "https://gitlab.com/b-reich/"
    target = "_blank"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter"
    weight = 3
    url = "https://twitter.com/chillfre4k/"
    target = "_blank"
[[params.social]]
    name = "e-mail"
    icon = "fa fa-envelope"
    weight = 4
    url = "mailto:contact@benjaminreich.de"
[[params.social]]
    name = "RSS"
    icon = "fa fa-rss"
    weight = 5
    url = "https://benjaminreich.de/index.xml"
    rel = "alternate"
    type = "application/rss+xml"


[languages]
    [languages.en]
        languageName = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About me"
            weight = 1
            url = "about/"

            #[[languages.en.menu.main]]
            #name = "Blog"
            #weight = 2
            #url = "posts/"

            #[[languages.en.menu.main]]
            #name = "Projects"
            #weight = 3
            #url = "projects/"
            